// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fractal.proto
// Protobuf C++ Version: 7.35.0

#ifndef fractal_2eproto_2epb_2eh
#define fractal_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_fractal_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_fractal_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_fractal_2eproto;
}  // extern "C"
namespace fractal {
class FractalPointMessage;
struct FractalPointMessageGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern FractalPointMessageGlobalsTypeInternal FractalPointMessage_globals_;
extern const ::google::protobuf::internal::ClassDataFull FractalPointMessage_class_data_;
#else
extern const FractalPointMessageGlobalsTypeInternal FractalPointMessage_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class FractalRequest;
struct FractalRequestGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern FractalRequestGlobalsTypeInternal FractalRequest_globals_;
extern const ::google::protobuf::internal::ClassDataFull FractalRequest_class_data_;
#else
extern const FractalRequestGlobalsTypeInternal FractalRequest_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class FractalResponse;
struct FractalResponseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern FractalResponseGlobalsTypeInternal FractalResponse_globals_;
extern const ::google::protobuf::internal::ClassDataFull FractalResponse_class_data_;
#else
extern const FractalResponseGlobalsTypeInternal FractalResponse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PingRequest;
struct PingRequestGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PingRequestGlobalsTypeInternal PingRequest_globals_;
extern const ::google::protobuf::internal::ClassDataFull PingRequest_class_data_;
#else
extern const PingRequestGlobalsTypeInternal PingRequest_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PingResponse;
struct PingResponseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PingResponseGlobalsTypeInternal PingResponse_globals_;
extern const ::google::protobuf::internal::ClassDataFull PingResponse_class_data_;
#else
extern const PingResponseGlobalsTypeInternal PingResponse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace fractal
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace fractal {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PingResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:fractal.PingResponse) */ {
 public:
  inline PingResponse() : PingResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PingResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PingResponse));
  }
#endif

  template <typename = void>
  explicit constexpr PingResponse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PingResponse(const PingResponse& from) : PingResponse(nullptr, from) {}
  inline PingResponse(PingResponse&& from) noexcept : PingResponse(nullptr, ::std::move(from)) {}
  inline PingResponse& operator=(const PingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PingResponse& operator=(PingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PingResponse& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PingResponse>(&PingResponse_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PingResponse& a, PingResponse& b) { a.Swap(&b); }
  inline void Swap(PingResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PingResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PingResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<PingResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PingResponse& from) { ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from); }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PingResponse& from) { ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from); }

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "fractal.PingResponse"; }

  explicit PingResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PingResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PingResponse& from);
  PingResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PingResponse&& from) noexcept
      : PingResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:fractal.PingResponse)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 0,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_fractal_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PingRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:fractal.PingRequest) */ {
 public:
  inline PingRequest() : PingRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PingRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PingRequest));
  }
#endif

  template <typename = void>
  explicit constexpr PingRequest(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PingRequest(const PingRequest& from) : PingRequest(nullptr, from) {}
  inline PingRequest(PingRequest&& from) noexcept : PingRequest(nullptr, ::std::move(from)) {}
  inline PingRequest& operator=(const PingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PingRequest& operator=(PingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PingRequest& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PingRequest>(&PingRequest_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PingRequest& a, PingRequest& b) { a.Swap(&b); }
  inline void Swap(PingRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PingRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PingRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<PingRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PingRequest& from) { ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from); }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PingRequest& from) { ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from); }

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "fractal.PingRequest"; }

  explicit PingRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PingRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PingRequest& from);
  PingRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PingRequest&& from) noexcept
      : PingRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:fractal.PingRequest)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 0,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_fractal_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED FractalRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:fractal.FractalRequest) */ {
 public:
  inline FractalRequest() : FractalRequest(nullptr) {}
  ~FractalRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FractalRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FractalRequest));
  }
#endif

  template <typename = void>
  explicit constexpr FractalRequest(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline FractalRequest(const FractalRequest& from) : FractalRequest(nullptr, from) {}
  inline FractalRequest(FractalRequest&& from) noexcept : FractalRequest(nullptr, ::std::move(from)) {}
  inline FractalRequest& operator=(const FractalRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FractalRequest& operator=(FractalRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const FractalRequest& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<FractalRequest>(&FractalRequest_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(FractalRequest& a, FractalRequest& b) { a.Swap(&b); }
  inline void Swap(FractalRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FractalRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] FractalRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FractalRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FractalRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FractalRequest& from) { FractalRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FractalRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "fractal.FractalRequest"; }

  explicit FractalRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FractalRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FractalRequest& from);
  FractalRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FractalRequest&& from) noexcept
      : FractalRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXMinFieldNumber = 2,
    kXMaxFieldNumber = 3,
    kKindFieldNumber = 1,
    kMaxIterationsFieldNumber = 6,
    kYMinFieldNumber = 4,
    kYMaxFieldNumber = 5,
  };
  // double x_min = 2;
  void clear_x_min() ;
  [[nodiscard]] double x_min() const;
  void set_x_min(double value);

  private:
  double _internal_x_min() const;
  void _internal_set_x_min(double value);

  public:
  // double x_max = 3;
  void clear_x_max() ;
  [[nodiscard]] double x_max() const;
  void set_x_max(double value);

  private:
  double _internal_x_max() const;
  void _internal_set_x_max(double value);

  public:
  // int32 kind = 1;
  void clear_kind() ;
  [[nodiscard]] ::int32_t kind() const;
  void set_kind(::int32_t value);

  private:
  ::int32_t _internal_kind() const;
  void _internal_set_kind(::int32_t value);

  public:
  // int32 max_iterations = 6;
  void clear_max_iterations() ;
  [[nodiscard]] ::int32_t max_iterations() const;
  void set_max_iterations(::int32_t value);

  private:
  ::int32_t _internal_max_iterations() const;
  void _internal_set_max_iterations(::int32_t value);

  public:
  // double y_min = 4;
  void clear_y_min() ;
  [[nodiscard]] double y_min() const;
  void set_y_min(double value);

  private:
  double _internal_y_min() const;
  void _internal_set_y_min(double value);

  public:
  // double y_max = 5;
  void clear_y_max() ;
  [[nodiscard]] double y_max() const;
  void set_y_max(double value);

  private:
  double _internal_y_max() const;
  void _internal_set_y_max(double value);

  public:
  // @@protoc_insertion_point(class_scope:fractal.FractalRequest)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 6,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FractalRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double x_min_;
    double x_max_;
    ::int32_t kind_;
    ::int32_t max_iterations_;
    double y_min_;
    double y_max_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fractal_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED FractalPointMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:fractal.FractalPointMessage) */ {
 public:
  inline FractalPointMessage() : FractalPointMessage(nullptr) {}
  ~FractalPointMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FractalPointMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FractalPointMessage));
  }
#endif

  template <typename = void>
  explicit constexpr FractalPointMessage(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline FractalPointMessage(const FractalPointMessage& from) : FractalPointMessage(nullptr, from) {}
  inline FractalPointMessage(FractalPointMessage&& from) noexcept : FractalPointMessage(nullptr, ::std::move(from)) {}
  inline FractalPointMessage& operator=(const FractalPointMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline FractalPointMessage& operator=(FractalPointMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const FractalPointMessage& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<FractalPointMessage>(&FractalPointMessage_globals_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(FractalPointMessage& a, FractalPointMessage& b) { a.Swap(&b); }
  inline void Swap(FractalPointMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FractalPointMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] FractalPointMessage* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FractalPointMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FractalPointMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FractalPointMessage& from) { FractalPointMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FractalPointMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "fractal.FractalPointMessage"; }

  explicit FractalPointMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FractalPointMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FractalPointMessage& from);
  FractalPointMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FractalPointMessage&& from) noexcept
      : FractalPointMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kIterationFieldNumber = 3,
  };
  // double x = 1;
  void clear_x() ;
  [[nodiscard]] double x() const;
  void set_x(double value);

  private:
  double _internal_x() const;
  void _internal_set_x(double value);

  public:
  // double y = 2;
  void clear_y() ;
  [[nodiscard]] double y() const;
  void set_y(double value);

  private:
  double _internal_y() const;
  void _internal_set_y(double value);

  public:
  // int32 iteration = 3;
  void clear_iteration() ;
  [[nodiscard]] ::int32_t iteration() const;
  void set_iteration(::int32_t value);

  private:
  ::int32_t _internal_iteration() const;
  void _internal_set_iteration(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:fractal.FractalPointMessage)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FractalPointMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double x_;
    double y_;
    ::int32_t iteration_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fractal_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED FractalResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:fractal.FractalResponse) */ {
 public:
  inline FractalResponse() : FractalResponse(nullptr) {}
  ~FractalResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FractalResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FractalResponse));
  }
#endif

  template <typename = void>
  explicit constexpr FractalResponse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline FractalResponse(const FractalResponse& from) : FractalResponse(nullptr, from) {}
  inline FractalResponse(FractalResponse&& from) noexcept : FractalResponse(nullptr, ::std::move(from)) {}
  inline FractalResponse& operator=(const FractalResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FractalResponse& operator=(FractalResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const FractalResponse& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<FractalResponse>(&FractalResponse_globals_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(FractalResponse& a, FractalResponse& b) { a.Swap(&b); }
  inline void Swap(FractalResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FractalResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] FractalResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FractalResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FractalResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FractalResponse& from) { FractalResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FractalResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "fractal.FractalResponse"; }

  explicit FractalResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FractalResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FractalResponse& from);
  FractalResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FractalResponse&& from) noexcept
      : FractalResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPointsFieldNumber = 1,
  };
  // repeated .fractal.FractalPointMessage points = 1;
  [[nodiscard]] int points_size()
      const;
  private:
  int _internal_points_size() const;

  public:
  void clear_points() ;
  [[nodiscard]] const ::fractal::FractalPointMessage& points(int index) const;
  [[nodiscard]] ::fractal::FractalPointMessage* PROTOBUF_NONNULL mutable_points(int index);
  ::fractal::FractalPointMessage* PROTOBUF_NONNULL add_points();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::fractal::FractalPointMessage>&
  points() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::fractal::FractalPointMessage>* PROTOBUF_NONNULL
  mutable_points();

  private:
  const ::google::protobuf::RepeatedPtrField<::fractal::FractalPointMessage>& _internal_points() const;
  ::google::protobuf::RepeatedPtrField<::fractal::FractalPointMessage>* PROTOBUF_NONNULL _internal_mutable_points();

  public:
  // @@protoc_insertion_point(class_scope:fractal.FractalResponse)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FractalResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::fractal::FractalPointMessage > points_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fractal_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PingRequest

// -------------------------------------------------------------------

// PingResponse

// -------------------------------------------------------------------

// FractalRequest

// int32 kind = 1;
inline void FractalRequest::clear_kind() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kind_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int32_t FractalRequest::kind() const {
  // @@protoc_insertion_point(field_get:fractal.FractalRequest.kind)
  return _internal_kind();
}
inline void FractalRequest::set_kind(::int32_t value) {
  _internal_set_kind(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:fractal.FractalRequest.kind)
}
inline ::int32_t FractalRequest::_internal_kind() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.kind_;
}
inline void FractalRequest::_internal_set_kind(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kind_ = value;
}

// double x_min = 2;
inline void FractalRequest::clear_x_min() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_min_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline double FractalRequest::x_min() const {
  // @@protoc_insertion_point(field_get:fractal.FractalRequest.x_min)
  return _internal_x_min();
}
inline void FractalRequest::set_x_min(double value) {
  _internal_set_x_min(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:fractal.FractalRequest.x_min)
}
inline double FractalRequest::_internal_x_min() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_min_;
}
inline void FractalRequest::_internal_set_x_min(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_min_ = value;
}

// double x_max = 3;
inline void FractalRequest::clear_x_max() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_max_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline double FractalRequest::x_max() const {
  // @@protoc_insertion_point(field_get:fractal.FractalRequest.x_max)
  return _internal_x_max();
}
inline void FractalRequest::set_x_max(double value) {
  _internal_set_x_max(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:fractal.FractalRequest.x_max)
}
inline double FractalRequest::_internal_x_max() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_max_;
}
inline void FractalRequest::_internal_set_x_max(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_max_ = value;
}

// double y_min = 4;
inline void FractalRequest::clear_y_min() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_min_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline double FractalRequest::y_min() const {
  // @@protoc_insertion_point(field_get:fractal.FractalRequest.y_min)
  return _internal_y_min();
}
inline void FractalRequest::set_y_min(double value) {
  _internal_set_y_min(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:fractal.FractalRequest.y_min)
}
inline double FractalRequest::_internal_y_min() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_min_;
}
inline void FractalRequest::_internal_set_y_min(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_min_ = value;
}

// double y_max = 5;
inline void FractalRequest::clear_y_max() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_max_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline double FractalRequest::y_max() const {
  // @@protoc_insertion_point(field_get:fractal.FractalRequest.y_max)
  return _internal_y_max();
}
inline void FractalRequest::set_y_max(double value) {
  _internal_set_y_max(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:fractal.FractalRequest.y_max)
}
inline double FractalRequest::_internal_y_max() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_max_;
}
inline void FractalRequest::_internal_set_y_max(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_max_ = value;
}

// int32 max_iterations = 6;
inline void FractalRequest::clear_max_iterations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_iterations_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int32_t FractalRequest::max_iterations() const {
  // @@protoc_insertion_point(field_get:fractal.FractalRequest.max_iterations)
  return _internal_max_iterations();
}
inline void FractalRequest::set_max_iterations(::int32_t value) {
  _internal_set_max_iterations(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:fractal.FractalRequest.max_iterations)
}
inline ::int32_t FractalRequest::_internal_max_iterations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_iterations_;
}
inline void FractalRequest::_internal_set_max_iterations(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_iterations_ = value;
}

// -------------------------------------------------------------------

// FractalPointMessage

// double x = 1;
inline void FractalPointMessage::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline double FractalPointMessage::x() const {
  // @@protoc_insertion_point(field_get:fractal.FractalPointMessage.x)
  return _internal_x();
}
inline void FractalPointMessage::set_x(double value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:fractal.FractalPointMessage.x)
}
inline double FractalPointMessage::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void FractalPointMessage::_internal_set_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// double y = 2;
inline void FractalPointMessage::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline double FractalPointMessage::y() const {
  // @@protoc_insertion_point(field_get:fractal.FractalPointMessage.y)
  return _internal_y();
}
inline void FractalPointMessage::set_y(double value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:fractal.FractalPointMessage.y)
}
inline double FractalPointMessage::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void FractalPointMessage::_internal_set_y(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// int32 iteration = 3;
inline void FractalPointMessage::clear_iteration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iteration_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int32_t FractalPointMessage::iteration() const {
  // @@protoc_insertion_point(field_get:fractal.FractalPointMessage.iteration)
  return _internal_iteration();
}
inline void FractalPointMessage::set_iteration(::int32_t value) {
  _internal_set_iteration(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:fractal.FractalPointMessage.iteration)
}
inline ::int32_t FractalPointMessage::_internal_iteration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iteration_;
}
inline void FractalPointMessage::_internal_set_iteration(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iteration_ = value;
}

// -------------------------------------------------------------------

// FractalResponse

// repeated .fractal.FractalPointMessage points = 1;
inline int FractalResponse::_internal_points_size() const {
  return _internal_points().size();
}
inline int FractalResponse::points_size() const {
  return _internal_points_size();
}
inline void FractalResponse::clear_points() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.points_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::fractal::FractalPointMessage& FractalResponse::points(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:fractal.FractalResponse.points)
  return _internal_points().Get(index);
}
inline ::fractal::FractalPointMessage* PROTOBUF_NONNULL FractalResponse::mutable_points(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:fractal.FractalResponse.points)
  return _internal_mutable_points()->Mutable(index);
}
inline ::fractal::FractalPointMessage* PROTOBUF_NONNULL FractalResponse::add_points()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::fractal::FractalPointMessage* _add =
      _internal_mutable_points()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:fractal.FractalResponse.points)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::fractal::FractalPointMessage>& FractalResponse::points() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:fractal.FractalResponse.points)
  return _internal_points();
}
inline ::google::protobuf::RepeatedPtrField<::fractal::FractalPointMessage>* PROTOBUF_NONNULL
FractalResponse::mutable_points() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:fractal.FractalResponse.points)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_points();
}
inline const ::google::protobuf::RepeatedPtrField<::fractal::FractalPointMessage>&
FractalResponse::_internal_points() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.points_;
}
inline ::google::protobuf::RepeatedPtrField<::fractal::FractalPointMessage>* PROTOBUF_NONNULL
FractalResponse::_internal_mutable_points() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.points_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace fractal


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // fractal_2eproto_2epb_2eh
