// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fractal.proto

#include "fractal.pb.h"
#include "fractal.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace fractal {

static const char* FractalService_method_names[] = {
  "/fractal.FractalService/Ping",
  "/fractal.FractalService/GenerateFractal",
};

std::unique_ptr< FractalService::Stub> FractalService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FractalService::Stub> stub(new FractalService::Stub(channel, options));
  return stub;
}

FractalService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Ping_(FractalService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GenerateFractal_(FractalService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FractalService::Stub::Ping(::grpc::ClientContext* context, const ::fractal::PingRequest& request, ::fractal::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fractal::PingRequest, ::fractal::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void FractalService::Stub::async::Ping(::grpc::ClientContext* context, const ::fractal::PingRequest* request, ::fractal::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fractal::PingRequest, ::fractal::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void FractalService::Stub::async::Ping(::grpc::ClientContext* context, const ::fractal::PingRequest* request, ::fractal::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fractal::PingResponse>* FractalService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::fractal::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fractal::PingResponse, ::fractal::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fractal::PingResponse>* FractalService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::fractal::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FractalService::Stub::GenerateFractal(::grpc::ClientContext* context, const ::fractal::FractalRequest& request, ::fractal::FractalResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fractal::FractalRequest, ::fractal::FractalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GenerateFractal_, context, request, response);
}

void FractalService::Stub::async::GenerateFractal(::grpc::ClientContext* context, const ::fractal::FractalRequest* request, ::fractal::FractalResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fractal::FractalRequest, ::fractal::FractalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GenerateFractal_, context, request, response, std::move(f));
}

void FractalService::Stub::async::GenerateFractal(::grpc::ClientContext* context, const ::fractal::FractalRequest* request, ::fractal::FractalResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GenerateFractal_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fractal::FractalResponse>* FractalService::Stub::PrepareAsyncGenerateFractalRaw(::grpc::ClientContext* context, const ::fractal::FractalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fractal::FractalResponse, ::fractal::FractalRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GenerateFractal_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fractal::FractalResponse>* FractalService::Stub::AsyncGenerateFractalRaw(::grpc::ClientContext* context, const ::fractal::FractalRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGenerateFractalRaw(context, request, cq);
  result->StartCall();
  return result;
}

FractalService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FractalService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FractalService::Service, ::fractal::PingRequest, ::fractal::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FractalService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fractal::PingRequest* req,
             ::fractal::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FractalService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FractalService::Service, ::fractal::FractalRequest, ::fractal::FractalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FractalService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fractal::FractalRequest* req,
             ::fractal::FractalResponse* resp) {
               return service->GenerateFractal(ctx, req, resp);
             }, this)));
}

FractalService::Service::~Service() {
}

::grpc::Status FractalService::Service::Ping(::grpc::ServerContext* context, const ::fractal::PingRequest* request, ::fractal::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FractalService::Service::GenerateFractal(::grpc::ServerContext* context, const ::fractal::FractalRequest* request, ::fractal::FractalResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fractal
#include <grpcpp/ports_undef.inc>

